export enum EventType {
  BIRTHDAY = 'BIRTHDAY',
  WEDDING = 'WEDDING',
  PARTY = 'PARTY',
  MEETING = 'MEETING',
  CONFERENCE = 'CONFERENCE',
  WORKSHOP = 'WORKSHOP',
  SEMINAR = 'SEMINAR',
  FUNERAL = 'FUNERAL',
  ILLNESS = 'ILLNESS',
  NEWBORN = 'NEWBORN',
  GRIEF = 'GRIEF',
}
